#!/usr/bin/env bash
# Run the thin Idaho ticks x402 door on apollo / the media box (LAN bind).
# Public go-live is later. Does not list on x402scan / Bazaar.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
export TICKS_DIR="${TICKS_DIR:-$HOME/projects/farm-plan/data/prices}"
export BIND_HOST="${BIND_HOST:-0.0.0.0}"
export PORT="${PORT:-4020}"

cd "$ROOT"
if [[ ! -f build/ticks-door.js ]]; then
  npm run build
fi

echo "TICKS_DIR=$TICKS_DIR"
echo "GMP_MD_DIR=${GMP_MD_DIR:-$HOME/projects/mcp-proxy/data/gmp-md}"
echo "SWISSPAR_DIR=${SWISSPAR_DIR:-$HOME/projects/mcp-proxy/data/swisspar}"
echo "PCAC_DIR=${PCAC_DIR:-$HOME/projects/mcp-proxy/data/pcac}"
echo "FTC_WL_DIR=${FTC_WL_DIR:-$HOME/projects/mcp-proxy/data/ftc-wl}"
echo "CFPB_ORDERS_DIR=${CFPB_ORDERS_DIR:-$HOME/projects/mcp-proxy/data/cfpb-orders}"
echo "OCC_CD_DIR=${OCC_CD_DIR:-$HOME/projects/mcp-proxy/data/occ-cd}"
echo "FDIC_ORDERS_DIR=${FDIC_ORDERS_DIR:-$HOME/projects/mcp-proxy/data/fdic-orders}"
echo "FRB_ORDERS_DIR=${FRB_ORDERS_DIR:-$HOME/projects/mcp-proxy/data/frb-orders}"
echo "NCUA_ORDERS_DIR=${NCUA_ORDERS_DIR:-$HOME/projects/mcp-proxy/data/ncua-orders}"
echo "FINCEN_ORDERS_DIR=${FINCEN_ORDERS_DIR:-$HOME/projects/mcp-proxy/data/fincen-orders}"
echo "FERC_ORDERS_DIR=${FERC_ORDERS_DIR:-$HOME/projects/mcp-proxy/data/ferc-orders}"
echo "OFAC_ORDERS_DIR=${OFAC_ORDERS_DIR:-$HOME/projects/mcp-proxy/data/ofac-orders}"
echo "BIS_ORDERS_DIR=${BIS_ORDERS_DIR:-$HOME/projects/mcp-proxy/data/bis-orders}"
echo "CFTC_ORDERS_DIR=${CFTC_ORDERS_DIR:-$HOME/projects/mcp-proxy/data/cftc-orders}"
echo "FIFRA_ORDERS_DIR=${FIFRA_ORDERS_DIR:-$HOME/projects/mcp-proxy/data/fifra-orders}"
echo "DENOVO_ORDERS_DIR=${DENOVO_ORDERS_DIR:-$HOME/projects/mcp-proxy/data/denovo-orders}"
echo "BIND_HOST=$BIND_HOST PORT=$PORT"
echo "unpaid /ticks (\$0.02): curl -i http://<lan-ip>:$PORT/ticks"
echo "unpaid /import-alerts (\$0.05): curl -i http://<lan-ip>:$PORT/import-alerts"
echo "unpaid /mariners (\$0.05): curl -i http://<lan-ip>:$PORT/mariners"
echo "unpaid /mariners-d11 (\$0.05): curl -i http://<lan-ip>:$PORT/mariners-d11"
echo "unpaid /mariners-d7 (\$0.05): curl -i http://<lan-ip>:$PORT/mariners-d7"
echo "unpaid /mariners-d8 (\$0.05): curl -i http://<lan-ip>:$PORT/mariners-d8"
echo "unpaid /warning-letters (\$0.05): curl -i http://<lan-ip>:$PORT/warning-letters"
echo "unpaid /untitled-letters (\$0.05): curl -i http://<lan-ip>:$PORT/untitled-letters"
echo "unpaid /awa (\$0.05): curl -i http://<lan-ip>:$PORT/awa"
echo "unpaid /swisspar (\$0.05): curl -i http://<lan-ip>:$PORT/swisspar"
echo "unpaid /pcac (\$0.05): curl -i http://<lan-ip>:$PORT/pcac"
echo "unpaid /ftc-wl (\$0.05): curl -i http://<lan-ip>:$PORT/ftc-wl"
echo "unpaid /cfpb-orders (\$0.05): curl -i http://<lan-ip>:$PORT/cfpb-orders"
echo "unpaid /occ-cd (\$0.05): curl -i http://<lan-ip>:$PORT/occ-cd"
echo "unpaid /fdic-orders (\$0.05): curl -i http://<lan-ip>:$PORT/fdic-orders"
echo "unpaid /frb-orders (\$0.05): curl -i http://<lan-ip>:$PORT/frb-orders"
echo "unpaid /ncua-orders (\$0.05): curl -i http://<lan-ip>:$PORT/ncua-orders"
echo "unpaid /fincen-orders (\$0.05): curl -i http://<lan-ip>:$PORT/fincen-orders"
echo "unpaid /ferc-orders (\$0.05): curl -i http://<lan-ip>:$PORT/ferc-orders"
echo "unpaid /ofac-orders (\$0.05): curl -i http://<lan-ip>:$PORT/ofac-orders"
echo "unpaid /bis-orders (\$0.05): curl -i http://<lan-ip>:$PORT/bis-orders"
echo "unpaid /cftc-orders (\$0.05): curl -i http://<lan-ip>:$PORT/cftc-orders"
echo "unpaid /fifra-orders (\$0.05): curl -i http://<lan-ip>:$PORT/fifra-orders"
echo "unpaid /denovo-orders (\$0.05): curl -i http://<lan-ip>:$PORT/denovo-orders"
echo "unpaid /form-483 (\$0.05): curl -i http://<lan-ip>:$PORT/form-483"
echo "unpaid /gmp (\$0.05): curl -i http://<lan-ip>:$PORT/gmp"
echo "unpaid /gmp-md (\$0.05): curl -i http://<lan-ip>:$PORT/gmp-md"
echo "free manifest: curl -s http://<lan-ip>:$PORT/import-alerts/manifest.json"
echo "free mariners: curl -s http://<lan-ip>:$PORT/mariners/manifest.json"
echo "free mariners-d11: curl -s http://<lan-ip>:$PORT/mariners-d11/manifest.json"
echo "free mariners-d7: curl -s http://<lan-ip>:$PORT/mariners-d7/manifest.json"
echo "free mariners-d8: curl -s http://<lan-ip>:$PORT/mariners-d8/manifest.json"
echo "free warning-letters: curl -s http://<lan-ip>:$PORT/warning-letters/manifest.json"
echo "free untitled-letters: curl -s http://<lan-ip>:$PORT/untitled-letters/manifest.json"
echo "free awa: curl -s http://<lan-ip>:$PORT/awa/manifest.json"
echo "free swisspar: curl -s http://<lan-ip>:$PORT/swisspar/manifest.json"
echo "free pcac: curl -s http://<lan-ip>:$PORT/pcac/manifest.json"
echo "free ftc-wl: curl -s http://<lan-ip>:$PORT/ftc-wl/manifest.json"
echo "free cfpb-orders: curl -s http://<lan-ip>:$PORT/cfpb-orders/manifest.json"
echo "free occ-cd: curl -s http://<lan-ip>:$PORT/occ-cd/manifest.json"
echo "free fdic-orders: curl -s http://<lan-ip>:$PORT/fdic-orders/manifest.json"
echo "free frb-orders: curl -s http://<lan-ip>:$PORT/frb-orders/manifest.json"
echo "free ncua-orders: curl -s http://<lan-ip>:$PORT/ncua-orders/manifest.json"
echo "free fincen-orders: curl -s http://<lan-ip>:$PORT/fincen-orders/manifest.json"
echo "free ferc-orders: curl -s http://<lan-ip>:$PORT/ferc-orders/manifest.json"
echo "free ofac-orders: curl -s http://<lan-ip>:$PORT/ofac-orders/manifest.json"
echo "free bis-orders: curl -s http://<lan-ip>:$PORT/bis-orders/manifest.json"
echo "free cftc-orders: curl -s http://<lan-ip>:$PORT/cftc-orders/manifest.json"
echo "free fifra-orders: curl -s http://<lan-ip>:$PORT/fifra-orders/manifest.json"
echo "free denovo-orders: curl -s http://<lan-ip>:$PORT/denovo-orders/manifest.json"
echo "free form-483: curl -s http://<lan-ip>:$PORT/form-483/manifest.json"
echo "free gmp: curl -s http://<lan-ip>:$PORT/gmp/manifest.json"
echo "free gmp-md: curl -s http://<lan-ip>:$PORT/gmp-md/manifest.json"
echo "paid smoke: X402_SKIP_SETTLE=1 … then curl -s http://<lan-ip>:$PORT/ticks -H 'X-PAYMENT: test'"
exec node build/ticks-door.js
